### ISSUE TITLE
Support for ATMEGA4808

### ISSUE THREAD

**Issue by donnm** [JChristensen/MCP9808#2]
I have an AVR-IoT board which is based on ATMEGA4808. To get this library working I had to comment out line 19 in MCP9808.cpp:

```
//    TWBR = ( (F_CPU / twiFreq) - 16) / 2;
```

and the outermost ifndef in MCP9808.h that includes the ```#error```.

Perhaps the library can be updated to be more flexible for such otherwise compatible devices.

**Comment by JChristensen** [comment]
Hi @donnm, I pushed a [dev branch](https://github.com/JChristensen/MCP9808/tree/dev) which may address the issue, but I don't have an ATmega4808 to test with. Would you please give it a try and let me know.

**Comment by donnm** [comment]
That works, thanks!

There is still a warning ``WARNING: library MCP9808 claims to run on (avr) architecture(s) and may be incompatible with your current board which runs on (megaavr) architecture(s).`` which can be fixed by changing the ``architectures``property in library.properties to:

``
architectures=avr,megaavr
``

**Comment by JChristensen** [comment]
Thanks for the test. I'll merge the changes and push a new version. I am aware of the architectures warning; my preference is to not advertise my libraries for platforms I do not personally work with, and therefore unable to test and debug first hand. Cheers!
